### ISSUE TITLE
getTenantAPIs() is not constant time

### ISSUE THREAD

**Issue by taylorking** [openwhisk/openwhisk-apigateway#85]
Because we don't have a mapping tenant -> api getTenantAPIs has to get all the APIs in redis, deserialize the json and check if it matches the tenantId.. This will be super slow if we take this into production. [here](https://github.com/openwhisk/apigateway/blob/master/api-gateway-config/scripts/lua/management/tenants.lua#L205)

**Comment by mhamann** [comment]
We do look up the list of APis by tenant, so while still not constant time, should be significantly more performant than sorting through every API in the datastore.

Am I missing something?

**Comment by mhamann** [comment]
Ah, I think you're referencing the management interface. The actual gateway path does not have this issue.

@songs what was the reasoning behind the current implementation?

**Comment by mhamann** [comment]
Also, this mgmt interface isn't used in a typical production scenario. Only in the standalone gateway.

**Comment by alexsong93** [comment]
@mhamann As you mentioned, this management interface is used only in the standalone gateway, and so there aren't as many tenants/APIs to account for. It was implemented this way so that how redis is structured doesn't deviate too much from how it's handled in production. 

However, it is true that this isn't the most optimal, and can be fixed by adding additional redis keys, as suggested by @taylorking.

**Comment by alexsong93** [comment]
FIxed via #113
